language: python
python:
- "3.7-dev"

install:
- pip install .
- pip install -r tests/requirements.txt

script:
- pytest --cov=./py_mocker tests

after_success:
- curl -s https://codecov.io/bash | bash

