language: python
dist: precise
python:
- "3.7"

install:
- pip install .
- pip install -r tests/requirements.txt

script:
- pytest --cov=./py_mocker tests

after_success:
- bash < (curl -s https://codecov.io/bash)
